import { Shop } from '@app/types/Shop';

const mockShops: Shop[] = [
  {
    id: '1',
    name: 'Sklep Centralny',
    address: 'ul. Główna 1 00-001, Warszawa',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=1',
  },
  {
    id: '2',
    name: 'Market Lokalny',
    address: 'ul. Boczna 15, 30-001 Kraków',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=2',
  },
  {
    id: '3',
    name: 'Supermarket Północny',
    address: 'ul. Morska 22 80-001, Gdańsk',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=3',
  },
  {
    id: '4',
    name: 'Mini Market Zachodni',
    address: 'ul. Zachodnia 7, Poznań',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=4',
  },
  {
    id: '5',
    name: 'Sklep Południowy',
    address: 'ul. Górska 11, Zakopane',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=5',
  },
  {
    id: '6',
    name: 'Market Wschodni',
    address: 'ul. Wschodnia 33, Lublin',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=6',
  },
  {
    id: '7',
    name: 'Delikatesy Centrum',
    address: 'ul. Centralna 44, Łódź',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=7',
  },
  {
    id: '8',
    name: 'Sklep Osiedlowy',
    address: 'ul. Osiedlowa 5, Wrocław',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=8',
  },
  {
    id: '9',
    name: 'Market Plus',
    address: 'ul. Długa 77, Szczecin',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=9',
  },
  {
    id: '10',
    name: 'Sklep u Marka',
    address: 'ul. Krótka 3, Katowice',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=10',
  },
  {
    id: '11',
    name: 'Supermarket XL',
    address: 'ul. Szeroka 100, Białystok',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=11',
  },
  {
    id: '12',
    name: 'Mini Market 24h',
    address: 'ul. Nocna 1, Rzeszów',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=12',
  },
  {
    id: '13',
    name: 'Sklep Familijny',
    address: 'ul. Rodzinna 15, Bydgoszcz',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=13',
  },
  {
    id: '14',
    name: 'Market na Rogu',
    address: 'ul. Narożna 2, Toruń',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=14',
  },
  {
    id: '15',
    name: 'Delikatesy Premium',
    address: 'ul. Luksusowa 88, Gdynia',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=15',
  },
  {
    id: '16',
    name: 'Sklep Ekonomiczny',
    address: 'ul. Tania 4, Częstochowa',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=16',
  },
  {
    id: '17',
    name: 'Market Miejski',
    address: 'ul. Ratuszowa 1, Radom',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=17',
  },
  {
    id: '18',
    name: 'Sklep pod Lipą',
    address: 'ul. Parkowa 22, Sosnowiec',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=18',
  },
  {
    id: '19',
    name: 'Supermarket Rodzinny',
    address: 'ul. Domowa 33, Kielce',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=19',
  },
  {
    id: '20',
    name: 'Mini Market Fresh',
    address: 'ul. Świeża 7, Gliwice',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=20',
  },
  {
    id: '21',
    name: 'Sklep Wygodny',
    address: 'ul. Komfortowa 55, Olsztyn',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=21',
  },
  {
    id: '22',
    name: 'Market Express',
    address: 'ul. Szybka 9, Bielsko-Biała',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=22',
  },
  {
    id: '23',
    name: 'Delikatesy Smak',
    address: 'ul. Smaczna 66, Bytom',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=23',
  },
  {
    id: '24',
    name: 'Sklep Tradycyjny',
    address: 'ul. Stara 12, Zielona Góra',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=24',
  },
  {
    id: '25',
    name: 'Market Słoneczny',
    address: 'ul. Słoneczna 44, Rybnik',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=25',
  },
  {
    id: '26',
    name: 'Sklep Poranny',
    address: 'ul. Poranna 8, Ruda Śląska',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=26',
  },
  {
    id: '27',
    name: 'Supermarket Nocny',
    address: 'ul. Księżycowa 99, Tychy',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=27',
  },
  {
    id: '28',
    name: 'Mini Market Zielony',
    address: 'ul. Zielona 17, Opole',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=28',
  },
  {
    id: '29',
    name: 'Sklep u Ani',
    address: 'ul. Przyjazna 23, Gorzów Wielkopolski',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=29',
  },
  {
    id: '30',
    name: 'Market Dobry',
    address: 'ul. Dobra 31, Dąbrowa Górnicza',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=30',
  },
  {
    id: '31',
    name: 'Delikatesy Lux',
    address: 'ul. Elegancka 77, Płock',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=31',
  },
  {
    id: '32',
    name: 'Sklep Oszczędny',
    address: 'ul. Tania 14, Wałbrzych',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=32',
  },
  {
    id: '33',
    name: 'Market Przyjazny',
    address: 'ul. Miła 28, Tarnów',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=33',
  },
  {
    id: '34',
    name: 'Sklep pod Dębem',
    address: 'ul. Leśna 19, Chorzów',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=34',
  },
  {
    id: '35',
    name: 'Supermarket Mega',
    address: 'ul. Duża 111, Koszalin',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=35',
  },
  {
    id: '36',
    name: 'Mini Market Mini',
    address: 'ul. Mała 6, Kalisz',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=36',
  },
  {
    id: '37',
    name: 'Sklep Szybki',
    address: 'ul. Ekspresowa 45, Legnica',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=37',
  },
  {
    id: '38',
    name: 'Market Świeży',
    address: 'ul. Świeża 38, Grudziądz',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=38',
  },
  {
    id: '39',
    name: 'Delikatesy Smaczne',
    address: 'ul. Smaczna 82, Słupsk',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=39',
  },
  {
    id: '40',
    name: 'Sklep Wiejski',
    address: 'ul. Wiejska 13, Jaworzno',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=40',
  },
  {
    id: '41',
    name: 'Market Miejski Plus',
    address: 'ul. Miejska 67, Jastrzębie-Zdrój',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=41',
  },
  {
    id: '42',
    name: 'Sklep Nowoczesny',
    address: 'ul. Nowoczesna 91, Nowy Sącz',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=42',
  },
  {
    id: '43',
    name: 'Supermarket Extra',
    address: 'ul. Dodatkowa 123, Jelenia Góra',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=43',
  },
  {
    id: '44',
    name: 'Mini Market Centrum',
    address: 'ul. Centralna 29, Siedlce',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=44',
  },
  {
    id: '45',
    name: 'Sklep Premium',
    address: 'ul. Luksusowa 144, Mysłowice',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=45',
  },
  {
    id: '46',
    name: 'Market Osiedlowy Plus',
    address: 'ul. Osiedlowa 16, Konin',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=46',
  },
  {
    id: '47',
    name: 'Delikatesy Centrum Plus',
    address: 'ul. Centralna 55, Piotrków Trybunalski',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=47',
  },
  {
    id: '48',
    name: 'Sklep na Rogu Plus',
    address: 'ul. Narożna 4, Inowrocław',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=48',
  },
  {
    id: '49',
    name: 'Market Familijny Plus',
    address: 'ul. Rodzinna 30, Lubin',
    type: 'FRANCHISE',
    imageUrl: 'https://picsum.photos/200/200?random=49',
  },
  {
    id: '50',
    name: 'Sklep Ekonomiczny Plus',
    address: 'ul. Oszczędna 8, Ostrów Wielkopolski',
    type: 'REGULAR',
    imageUrl: 'https://picsum.photos/200/200?random=50',
  },
];

const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

export async function getShops(): Promise<Shop[]> {
  try {
    // W rzeczywistej aplikacji tutaj byłoby wywołanie API
    // const response = await axios.get<Shop[]>('/api/shops');
    // return response.data;

    // Na potrzeby demonstracji używamy mocków
    await delay(1000);
    return mockShops;
  } catch (error) {
    console.error('Failed to fetch shops:', error);
    throw error;
  }
}
